# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uuid', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=63, null=True)),
                ('owner', models.CharField(max_length=63, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('is_private', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together=set([('uuid', 'is_private')]),
        ),
    ]
