# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='key',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
    ]
