# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('mac_address', models.CharField(max_length=255, null=True)),
                ('os', models.CharField(max_length=64, null=True)),
                ('os_version', models.CharField(max_length=128, null=True)),
                ('core_cpu', models.IntegerField(default=4)),
                ('total_memory', models.BigIntegerField(default=0)),
                ('volume_size', models.BigIntegerField(default=0)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('instance_group_name', models.TextField(max_length=128)),
                ('note', models.TextField(max_length=255, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.Instance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterIndexTogether(
            name='instancedetails',
            index_together=set([('os', 'core_cpu')]),
        ),
    ]
