# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0002_auto_20170801_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancetypes',
            name='type_instances',
            field=models.CharField(choices=[('VM', 'Virturl Machine'), ('EC2', 'Amazon Web Service'), ('AZURE', 'Cloud Computing Platform'), ('GCL', 'Google Cloud Platform')], default='VM', max_length=16, null=True),
        ),
    ]
