# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0003_auto_20170801_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancetypes',
            name='type_instances_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='instancetypes',
            name='type_instances',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
